# Generated by Django 5.1.5 on 2025-08-01 09:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theses", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thesis",
            name="document",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="documents"
            ),
        ),
    ]
