# Generated by Django 5.1.5 on 2025-08-01 10:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theses", "0004_remove_thesis_document_thesis_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="thesis",
            name="document",
            field=cloudinary.models.CloudinaryField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
