# Generated by Django 5.1.5 on 2025-08-01 23:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theses", "0006_remove_thesis_file_alter_thesis_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thesis",
            name="document",
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
